use std::io::Write;

use super::write_parallel;
use crate::{Mesh, Result};

/// Appends a float in shortest round-trip form; `-0` becomes `0`.
#[inline]
fn put_float(buf: &mut Vec<u8>, v: f32) {
    buf.push(b' ');
    buf.extend_from_slice(ryu::Buffer::new().format_finite(v + 0.0).as_bytes());
}

pub(super) fn write(mesh: &Mesh, out: &mut impl Write) -> Result<()> {
    writeln!(
        out,
        "# Generated by hmterrain {}",
        env!("CARGO_PKG_VERSION")
    )?;
    writeln!(
        out,
        "# {} vertices, {} triangles\no terrain",
        mesh.vertex_count(),
        mesh.triangle_count()
    )?;

    write_parallel(out, &mesh.positions, 32, |buf, _, p| {
        buf.push(b'v');
        for &c in p {
            put_float(buf, c);
        }
        buf.push(b'\n');
    })?;
    if let Some(uvs) = &mesh.uvs {
        // OBJ puts the texture origin at the bottom-left corner.
        write_parallel(out, uvs, 24, |buf, _, uv| {
            buf.extend_from_slice(b"vt");
            put_float(buf, uv[0]);
            put_float(buf, 1.0 - uv[1]);
            buf.push(b'\n');
        })?;
    }
    if let Some(normals) = &mesh.normals {
        write_parallel(out, normals, 32, |buf, _, n| {
            buf.extend_from_slice(b"vn");
            for &c in n {
                put_float(buf, c);
            }
            buf.push(b'\n');
        })?;
    }

    // Vertex, texture and normal indices are identical and 1-based.
    let suffix: &[u8] = match (mesh.uvs.is_some(), mesh.normals.is_some()) {
        (true, true) => b"/#/#",
        (true, false) => b"/#",
        (false, true) => b"//#",
        (false, false) => b"",
    };
    write_parallel(out, &mesh.indices, 48, |buf, _, tri| {
        buf.push(b'f');
        let mut num = itoa::Buffer::new();
        for &v in tri {
            let index = num.format(u64::from(v) + 1).as_bytes();
            buf.push(b' ');
            buf.extend_from_slice(index);
            for &b in suffix {
                if b == b'#' {
                    buf.extend_from_slice(index);
                } else {
                    buf.push(b);
                }
            }
        }
        buf.push(b'\n');
    })?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::MeshOptions;
    use crate::export::test_support::sample_mesh;

    fn render(options: &MeshOptions) -> (Mesh, String) {
        let mesh = sample_mesh(options);
        let mut out = Vec::new();
        write(&mesh, &mut out).unwrap();
        (mesh, String::from_utf8(out).unwrap())
    }

    #[test]
    fn round_trips_positions_and_faces() {
        let (mesh, text) = render(&MeshOptions::default());
        let vertices: Vec<[f32; 3]> = text
            .lines()
            .filter_map(|l| l.strip_prefix("v "))
            .map(|l| {
                let v: Vec<f32> = l.split(' ').map(|s| s.parse().unwrap()).collect();
                [v[0], v[1], v[2]]
            })
            .collect();
        assert_eq!(vertices, mesh.positions);
        assert_eq!(
            text.lines().filter(|l| l.starts_with("vt ")).count(),
            mesh.vertex_count()
        );
        assert_eq!(
            text.lines().filter(|l| l.starts_with("vn ")).count(),
            mesh.vertex_count()
        );
        let faces: Vec<&str> = text.lines().filter(|l| l.starts_with("f ")).collect();
        assert_eq!(faces.len(), mesh.triangle_count());
        let [a, b, c] = mesh.indices[0].map(|i| i + 1);
        assert_eq!(faces[0], format!("f {a}/{a}/{a} {b}/{b}/{b} {c}/{c}/{c}"));
    }

    #[test]
    fn face_syntax_matches_attributes() {
        let bare = MeshOptions {
            normals: false,
            uvs: false,
            ..MeshOptions::default()
        };
        let (mesh, text) = render(&bare);
        let [a, b, c] = mesh.indices[0].map(|i| i + 1);
        assert!(text.contains(&format!("\nf {a} {b} {c}\n")));
        assert!(!text.contains("vt ") && !text.contains("vn "));

        let normals_only = MeshOptions {
            uvs: false,
            ..MeshOptions::default()
        };
        let (_, text) = render(&normals_only);
        assert!(text.contains(&format!("\nf {a}//{a} {b}//{b} {c}//{c}\n")));
    }

    #[test]
    fn numbers_use_dot_decimal_separator() {
        let (_, text) = render(&MeshOptions::default());
        assert!(!text.lines().any(|l| l.starts_with('v') && l.contains(',')));
        assert!(!text.contains("-0.0 ") && !text.contains("-0.0\n"));
    }
}
