use std::fmt::Write as _;
use std::io::Write;

use super::{put_f32s, write_parallel};
use crate::{Mesh, Result};

pub(super) fn write(mesh: &Mesh, out: &mut impl Write) -> Result<()> {
    let mut header = format!(
        "ply\nformat binary_little_endian 1.0\ncomment Generated by hmterrain {}\nelement vertex {}\n\
         property float x\nproperty float y\nproperty float z\n",
        env!("CARGO_PKG_VERSION"),
        mesh.vertex_count()
    );
    if mesh.normals.is_some() {
        header.push_str("property float nx\nproperty float ny\nproperty float nz\n");
    }
    if mesh.uvs.is_some() {
        header.push_str("property float s\nproperty float t\n");
    }
    let _ = write!(
        header,
        "element face {}\nproperty list uchar uint vertex_indices\nend_header\n",
        mesh.triangle_count()
    );
    out.write_all(header.as_bytes())?;

    let (normals, uvs) = (mesh.normals.as_deref(), mesh.uvs.as_deref());
    write_parallel(out, &mesh.positions, 32, |buf, i, p| {
        put_f32s(buf, p);
        if let Some(n) = normals {
            put_f32s(buf, &n[i]);
        }
        if let Some(uv) = uvs {
            // PLY tools expect the texture origin at the bottom-left corner.
            put_f32s(buf, &[uv[i][0], 1.0 - uv[i][1]]);
        }
    })?;
    write_parallel(out, &mesh.indices, 13, |buf, _, tri| {
        buf.push(3);
        for v in tri {
            buf.extend_from_slice(&v.to_le_bytes());
        }
    })?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::MeshOptions;
    use crate::export::test_support::sample_mesh;

    #[test]
    fn header_matches_body() {
        for (normals, uvs, floats) in [(true, true, 8), (false, false, 3), (true, false, 6)] {
            let mesh = sample_mesh(&MeshOptions {
                normals,
                uvs,
                ..MeshOptions::default()
            });
            let mut out = Vec::new();
            write(&mesh, &mut out).unwrap();
            let end = out.windows(11).position(|w| w == b"end_header\n").unwrap() + 11;
            let header = std::str::from_utf8(&out[..end]).unwrap();
            assert!(header.contains(&format!("element vertex {}\n", mesh.vertex_count())));
            assert!(header.contains(&format!("element face {}\n", mesh.triangle_count())));
            assert_eq!(header.contains("property float nx"), normals);
            assert_eq!(header.contains("property float s"), uvs);
            let body = out.len() - end;
            assert_eq!(
                body,
                mesh.vertex_count() * 4 * floats + mesh.triangle_count() * 13
            );
            let first = f32::from_le_bytes(out[end..end + 4].try_into().unwrap());
            assert_eq!(first, mesh.positions[0][0]);
        }
    }
}
