use std::io::Write;

use super::{put_f32s, write_parallel};
use crate::mesh::{face_normal, normalize};
use crate::{Error, Mesh, Result};

pub(super) fn write(mesh: &Mesh, out: &mut impl Write) -> Result<()> {
    let count = u32::try_from(mesh.triangle_count())
        .map_err(|_| Error::TooLarge("binary STL holds at most 2^32 - 1 triangles".into()))?;
    let mut header = [b' '; 80];
    let title = concat!(
        "Binary STL generated by hmterrain ",
        env!("CARGO_PKG_VERSION")
    );
    header[..title.len()].copy_from_slice(title.as_bytes());
    out.write_all(&header)?;
    out.write_all(&count.to_le_bytes())?;

    let p = &mesh.positions;
    write_parallel(out, &mesh.indices, 50, |buf, _, &[a, b, c]| {
        let [a, b, c] = [p[a as usize], p[b as usize], p[c as usize]];
        put_f32s(buf, &normalize(face_normal(a, b, c), [0.0, 0.0, 0.0]));
        for v in [a, b, c] {
            put_f32s(buf, &v);
        }
        buf.extend_from_slice(&[0, 0]);
    })?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::MeshOptions;
    use crate::export::test_support::sample_mesh;

    #[test]
    fn layout_and_normals() {
        let mesh = sample_mesh(&MeshOptions::default());
        let mut out = Vec::new();
        write(&mesh, &mut out).unwrap();
        assert_eq!(out.len(), 84 + 50 * mesh.triangle_count());
        assert!(out.starts_with(b"Binary STL generated by hmterrain"));
        let count = u32::from_le_bytes(out[80..84].try_into().unwrap());
        assert_eq!(count as usize, mesh.triangle_count());
        let f = |o: usize| f32::from_le_bytes(out[o..o + 4].try_into().unwrap());
        // First facet: unit normal pointing up, then the first vertex.
        let n = [f(84), f(88), f(92)];
        assert!(n[1] > 0.0 && ((n[0] * n[0] + n[1] * n[1] + n[2] * n[2]) - 1.0).abs() < 1e-5);
        assert_eq!(
            [f(96), f(100), f(104)],
            mesh.positions[mesh.indices[0][0] as usize]
        );
    }
}
